### PR TITLE
Fixing the name field when enumerating registry keys and values

### LINKED ISSUE #413: registry enumeration has a bug with the key name field size and m_name_length getting out of sync.
This shows a bug in the intermediate representations of the iterator. Note that passing by value works, by creating a copy and re-syncing the std::wstring size. 

it seems when the size of the value name gets smaller is when this bug occurs.

it seems `m_name_length` is for the bstr case and I don't have much sympathy for code that needs the value name in that format. can we simplify this and get rid of m_name_length or not use a std::wstring in this case to avoid the duplication and incoherence it creates?

```cpp
        // failing test. post this issue on github
        TEST_METHOD(VerifyRegistryEnumeratorWorksWithByRefParameter)
        {
            PCWSTR subKey = LR"(BugRepro)";
            auto extensionsIds = wil::reg::create_unique_key(HKEY_CURRENT_USER_LOCAL_SETTINGS, subKey, wil::reg::key_access::readwrite);
            wil::reg::set_value_string(extensionsIds.get(), L"{00021401-0000-0000-C000-000000000046}", L"");
            wil::reg::set_value_string(extensionsIds.get(), L"{66742402-F9B9-11D1-A202-0000F81FEDEE}", L"");
            wil::reg::set_value_string(extensionsIds.get(), L"Windows.Foundation.Uri", L"");
            wil::reg::set_value_string(extensionsIds.get(), L"Windows.Foundation.PropertyValue", L"");
            wil::reg::set_value_string(extensionsIds.get(), L"Wrong", L"{F8F24682-0E3B-4BE3-B6F5-1EC33AFE207D}");

            auto begin = wil::reg::value_iterator{ extensionsIds.get() };
            auto end = wil::reg::value_iterator{};

            std::for_each(begin, end, [&](auto nameAndType) // this works
            {
                cpp_unit::Logger::WriteMessage(nameAndType.name.c_str());
                auto size = wcslen(nameAndType.name.c_str());
                cpp_unit::Assert::IsTrue(size == nameAndType.name.size());
            });

            std::for_each(begin, end, [&](auto&& nameAndType) // this fails with the size assert below
            {
                cpp_unit::Logger::WriteMessage(nameAndType.name.c_str());
                auto size = wcslen(nameAndType.name.c_str());
                cpp_unit::Assert::IsTrue(size == nameAndType.name.size()); // failing
            });
        }
```

### PR DESCRIPTION
**Pull request by keith-horton**
When using std::wstring as the name type when enumerating registry names and values, we need to fix the internal consistency of the std::wstring object + have it correctly sync with the name_size property in the parent object.

Fixes #413

### CODE REVIEW

File: include/wil/registry_helpers.h [hunk 1]
```diff
@@ -28,1081 +28,1084 @@
...
-        // Open key for reading.
-        read,
-
-        // Open key for reading and writing. Equivalent to KEY_ALL_ACCESS.
-        readwrite,
-    };
-
-    /// @cond
-    namespace reg_view_details
+    namespace reg
```
Comment (dunhor) [inline include/wil/registry_helpers.h:31]: Please run `clang-format` on this change

**Comment by dunhor** [comment]
Fixes #413

**Comment by dunhor** [comment]
This should add the test Chris described in #413 for current & future validation

File: include/wil/registry_helpers.h [hunk 2]
```diff
@@ -1617,7 +1644,11 @@ namespace reg
                 if (error == ERROR_SUCCESS)
                 {
                     // some types, like std::wstring, cannot have embedded nulls
-                    ::wil::reg::reg_view_details::reg_value_type_info::trim_buffer(name);
+                    // if we trimmed anything, we must also get the new sizej
```
Comment (dunhor) [inline include/wil/registry_helpers.h:1647]:
```suggestion
                    // if we trimmed anything, we must also get the new size
```

File: include/wil/registry_helpers.h [hunk 3]
```diff
@@ -1367,6 +1370,27 @@ namespace reg
...
+                {
+                    return 0;
+                }
+                return new_length;
+            }
+
+            // continue to use the existing buffer since the requested length is less than or equals to the current length
+            clear_name(name, current_length);
+            return current_length;
+        }
```
Comment (dunhor) [inline include/wil/registry_helpers.h:1392]:
```suggestion
#if defined(WIL_ENABLE_EXCEPTIONS) && defined(_STRING_)
        // failure returns zero
        inline size_t resize_name(::std::wstring& name, size_t current_length, size_t new_length) WI_NOEXCEPT
        {
            // because std::wstring encodes the size within its object, we must resize whenever the 2 are not equal
            // not just when the new_length is greater than the current_length -- which is correct for types that don't encode their size
            if (new_length != current_length)
            {
                // resize_buffer takes size in bytes
                if (FAILED(::wil::reg::reg_view_details::reg_value_type_info::resize_buffer(
                        name, static_cast<DWORD>(new_length * sizeof(wchar_t)))))
                {
                    return 0;
                }
                return new_length;
            }

            // continue to use the existing buffer since the requested length is less than or equals to the current length
            clear_name(name, current_length);
            return current_length;
        }
#endif
```
Or move it up to a pre-existing guard. This should fix your build failure

**Comment by ChrisGuzak** [comment]
out-side of the scope of this change... 
- I see the default value of a key is not considered value as `is_valid()` for the `std::wstring` case uses `!empty()`
- growing the buffer size only by `iterator_default_buffer_length` (16) does not work well if the names are large. this should use an exponential growth strategy.
- it is a bummer we have to allocate the value names. value names are 16k or so, but key names < 255 (or so).
- using a bstr as a temporary representation is very odd. LocalAlloc or other allocators are more conventional. 
- most clients are better off with a **fixed sized** "max value name" constant. 
  - this could be a template param for testing and letting callers pay for what they need. 
  - we could have another "dynamic" mode, also a template param with `if constexpr` enabled code that does the allocations for those that must have it.

**Comment by keith-horton** [comment]
> This should add the test Chris described in #413 for current & future validation

Yep, added a set of new tests that this helped uncover.

**Comment by keith-horton** [comment]
> out-side of the scope of this change...
> 
> * using `BSTR` as the key name is odd.
>   
>   * **LocalSize could be used to determine the size, avoiding the need for the separate size book-keeping needed because of `BSTR` that is the cause of this bug.**
>   * LocalAlloc or other allocators are more conventional. our guidelines say, "don't use BSTRs in new code".
> * it is a bummer we have to allocate the value names. value names are 16k or so, but key names < 255 (or so).
> * most clients are better off with a **fixed sized** "max value name" constant.
>   
>   * this could be a template param for testing and letting callers pay for what they need.
>   * we could have another "dynamic" mode, also a template param with `if constexpr` enabled code that does the allocations for those that must have it.
> * The default value of a key (that with an empty string for a name) may have incorrect behavior as `is_valid()` for the `std::wstring` case uses `!empty()` (code below)
> * growing the buffer size only by `iterator_default_buffer_length` (16) does not work well if the names are large. an exponential growth strategy seems better.
> 
> What do you think about the idea of switching to using `LocalAlloc` and `LocalSize` to get rid of `m_current_length`?
> 
> ```c++
>             inline bool is_valid(const ::std::wstring& name) WI_NOEXCEPT
>             {
>                 return !name.empty();
>             }
> ```

Lots of good feedback.

I've addressed some of it in this most recent push. Will be thinking about some of the other feedback.

**Review by ChrisGuzak — APPROVED** [review]
great response to my comments Keith! much improved.
